train:
  test_size: 0.2
  random_state: 42
gridsearch:
  cv: 5
  scoring: 'r2'
  n_jobs: -1
  verbose: 1
  param_grid:
    n_estimators: [50, 100, 200, 300]
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2]
    max_features: ['log2', 'sqrt']
    bootstrap: [True]